apply plugin: 'com.google.dagger.hilt.android'
dependencies {
    /**
     * 路由库
     */
    implementation libs.therouter
    ksp libs.therouter.apt

    // 依赖注入框架
    implementation(libs.hilt.android) {
        exclude group: 'androidx.lifecycle'
    }
    ksp libs.hilt.compiler
}

dependencies {
    compileOnly project(":lib_modules:lib_resource")
}