apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"
apply plugin: 'org.jetbrains.kotlin.android'

def isApplication = project.name == debug_module_name

android {
    namespace 'com.gw.cp_mine'

    defaultConfig {
        if (isApplication) {
            applicationId "com.gw.cp_mine"
        }
    }

    /**
     * 资源文件前缀
     */
    resourcePrefix("mine_")

}

dependencies {
    // 重启app 库
    compileOnly libs.process.phoenix

    // PictureSelector 基础 (必须)
    implementation libs.picture.selector

    // adapter
    implementation libs.recyclerview.adapter.helper

    // 滚动选择器
    implementation libs.wheel.picker

    // 图片加载框架
    implementation libs.glide

    // 文件压缩
    implementation libs.zip4j
}

dependencies {
    implementation project(":component_modules:component_device_share_api")
    implementation project(":component_modules:component_family_api")
    implementation project(":component_modules:component_account_api")
    implementation project(":component_modules:component_mine_api")
    implementation project(":component_modules:component_msg_api")
    implementation project(":component_modules:component_config_api")

    implementation(libs.reoqoo.component.plugin.service.api)
    implementation(libs.reoqoo.component.webview.api)
    implementation(libs.reoqoo.component.website.api)
    implementation(libs.reoqoo.component.upgrade.api)
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)
    implementation(libs.reoqoo.component.app.setting.api)
}

dependencies {
    implementation(libs.reoqoo.lib.log)
    implementation(libs.reoqoo.lib.webview)
//    if (isApplication) {
//        // 屏幕适配
//        implementation libs.auto.size
//    }
}