// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
        maven {
            setUrl("https://jitpack.io")
            content {
                includeGroup("com.github.aasitnikov")
            }
        }
    }
    dependencies {
        // 增加Android Gradle插件版本号配置，{version}为实际的Gradle插件版本号，例如7.1.1。
        classpath (libs.android.gradle.plugin)
    }

    project.ext.set("isApp", false)

}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.kapt) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.hilt.android) apply false
    alias(libs.plugins.therouter.agp8) apply false
    alias(libs.plugins.navigation.safeargs) apply false
    alias(libs.plugins.google.gms.services) apply false
    alias(libs.plugins.sensors.analytics) apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
