import com.gw.buildsrc.version.Versions

// Top-level build file where you can add configuration options common to all sub-projects/modules.
// TODO 需要修改为 kts的配置
buildscript {
    ext {
        agp_version = '8.9.1'
    }
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
        maven {
            setUrl("https://jitpack.io")
            content {
                includeGroup("com.github.aasitnikov")
            }
        }
    }
    dependencies {
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:${Versions.AndroidUtilsVersions.VERSION_NAVIGATION}")
//        classpath 'com.github.aasitnikov:fat-aar-android:1.4.1'
        classpath "org.jetbrains.kotlin:kotlin-serialization:2.2.20"
        // 增加Android Gradle插件版本号配置，{version}为实际的Gradle插件版本号，例如7.1.1。
        classpath (libs.android.gradle.plugin)
        // 增加AGC插件配置，请您参见AGC插件依赖关系选择合适的AGC插件版本。
    }

    project.ext.set("isApp", false)

}

plugins {
    id("com.android.application") version '8.9.1' apply false
    id("com.android.library") version "8.9.1" apply false
//    id("org.jetbrains.kotlin.android") version "2.2.20" apply false
    id("cn.therouter.agp8") version "1.2.2" apply false
    id("com.google.dagger.hilt.android") version "2.57.1" apply false
    id("com.sensorsdata.analytics.android") version "4.0.2" apply false
    id("com.google.gms.google-services") version "4.3.15" apply false
//    id("org.jetbrains.kotlin.plugin.compose") version "2.2.20" apply false
    // Kotlin compose
    alias(libs.plugins.kotlin.compose) apply false
    // Kotlin android
    alias(libs.plugins.kotlin.android) apply false
    // Kotlin kapt
    alias(libs.plugins.kotlin.kapt) apply false
}

allprojects {

    // 全局统一 Kotlin 相关依赖版本，防止传递依赖拉入不兼容的版本
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                if (details.requested.name in ['kotlin-stdlib', 'kotlin-stdlib-jdk7', 'kotlin-stdlib-jdk8', 'kotlin-reflect']) {
                    details.useVersion '2.2.20'
                }
            }
        }
    }
}

// TODO主要用于插件源码依赖
//apply from: "config.gradle"

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
