import com.gw.buildsrc.version.Versions

// Top-level build file where you can add configuration options common to all sub-projects/modules.
// TODO 需要修改为 kts的配置
buildscript {
    ext {
        agp_version = '8.9.1'
    }
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        mavenCentral()
        maven {
            setUrl("https://jitpack.io")
            content {
                includeGroup("com.github.aasitnikov")
            }
        }
    }
    dependencies {
        // 增加Android Gradle插件版本号配置，{version}为实际的Gradle插件版本号，例如7.1.1。
        classpath (libs.android.gradle.plugin)
    }

    project.ext.set("isApp", false)

}

plugins {
    alias(libs.plugins.therouter.agp8) apply false
    alias(libs.plugins.hilt.android) apply false
    // Kotlin compose
    alias(libs.plugins.kotlin.compose) apply false
    // Kotlin 序列化
    alias(libs.plugins.kotlin.serialization) apply false
    // Android application
    alias(libs.plugins.android.application) apply false
    // Android library
    alias(libs.plugins.android.library) apply false
    // Kotlin android
    alias(libs.plugins.kotlin.android) apply false
    // Kotlin kapt
    alias(libs.plugins.kotlin.kapt) apply false
    // Navigation
    alias(libs.plugins.navigation.safeargs) apply false
    // 神策分析
    alias(libs.plugins.sensors.analytics) apply false
    // Google GMS
    alias(libs.plugins.google.gms.services) apply false
}

allprojects {

    // 全局统一 Kotlin 相关依赖版本，防止传递依赖拉入不兼容的版本
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                if (details.requested.version in ['KOTLIN_2_0', 'KOTLIN_2_1'] ||
                        details.requested.name in ['kotlin-stdlib', 'kotlin-stdlib-jdk7', 'kotlin-stdlib-jdk8', 'kotlin-reflect']) {
                    details.useVersion Versions.BuildVersions.VERSION_KOTLIN
                }
            }
        }
    }
}

// TODO主要用于插件源码依赖
//apply from: "config.gradle"

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
