apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"
apply from: "${rootDir.absolutePath}/script/gradle/reoqoo.gradle"

android {
    namespace 'com.reoqoo.main'

    // 添加默认配置，指定支持的语言
    defaultConfig {
        resConfigs "en", "ko" // 仅支持英语和韩语
    }

    sourceSets {
        getByName("iptime") {
            res.srcDirs("src/iptime/res")
        }
    }
}

dependencies {
    implementation(libs.reoqoo.lib.utils)
    implementation(libs.reoqoo.lib.router)
    implementation(libs.reoqoo.lib.architecture)
    implementation(libs.reoqoo.lib.log)
    implementation(libs.reoqoo.lib.http)
    implementation(libs.reoqoo.component.iotapi.plugin)
    implementation(libs.reoqoo.component.iotapi.plugin.api)
    implementation(libs.reoqoo.component.iotapi.plugin.opt)
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)
}

dependencies {
    implementation project(":main_api")

    implementation project(":component_modules:component_family")
    implementation project(":component_modules:component_family_api")

    implementation project(":component_modules:component_account")
    implementation project(":component_modules:component_account_api")

    implementation project(":component_modules:component_device_share")
    implementation project(":component_modules:component_device_share_api")

    implementation project(":component_modules:component_house_watch")
    implementation project(":component_modules:component_house_watch_api")

    implementation project(":component_modules:component_mine")
    implementation project(":component_modules:component_mine_api")

    implementation project(":component_modules:component_config")
    implementation project(":component_modules:component_config_api")

    implementation project(":component_modules:component_msg")
    implementation project(":component_modules:component_msg_api")

    implementation project(":component_modules:component_push")
    implementation project(":component_modules:component_push_api")

    implementation(libs.reoqoo.component.webview)
    implementation(libs.reoqoo.component.webview.api)

    implementation(libs.reoqoo.component.website)
    implementation(libs.reoqoo.component.website.api)

    implementation(libs.reoqoo.component.plugin.service)
    implementation(libs.reoqoo.component.plugin.service.api)

    implementation(libs.reoqoo.component.debug)
    implementation(libs.reoqoo.component.debug.api)

    implementation(libs.reoqoo.component.upgrade)
    implementation(libs.reoqoo.component.upgrade.api)

    implementation(libs.reoqoo.component.config.net)
    implementation(libs.reoqoo.component.config.net.api)

    implementation(libs.reoqoo.component.app.setting)
    implementation(libs.reoqoo.component.app.setting.api)
}

dependencies {
    implementation libs.process.phoenix
    implementation libs.gw.base.crash
    implementation libs.gw.base.lifecycle

    // 添加腾讯的回音消除依赖
    implementation libs.gw.txtraevoip
}