apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"

android {
    namespace 'com.gw.component_push'

    /**
     * 资源文件前缀
     */
    resourcePrefix("push_")

}

dependencies {
    implementation libs.gw.push.google

    implementation libs.firebase.messaging

    implementation(libs.moshi.kotlin)

    /**
     * 云存相关
     */
    implementation libs.gw.iot.vas

    /**
     * 技威云存播放器库
     */
    implementation(libs.gw.cloud.player)
}

dependencies {
    implementation(libs.reoqoo.lib.iotvideo)
    implementation(libs.reoqoo.component.plugin.service.api)
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)

    implementation project(path: ':component_modules:component_push_api')
    implementation project(path: ':component_modules:component_config_api')
    implementation project(path: ':component_modules:component_family_api')
    implementation project(path: ':component_modules:component_account_api')
}