apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"

def isApplication = project.name == debug_module_name

android {
    namespace 'com.gw.cp_msg'

    defaultConfig {
        if (isApplication) {
            applicationId "com.gw.cp_msg"
        }
    }

    /**
     * 资源文件前缀
     */
    resourcePrefix("msg_")
}

dependencies {
    implementation(libs.reoqoo.lib.log)
    implementation(libs.reoqoo.lib.http)
    implementation(libs.reoqoo.lib.webview)
}

dependencies {
    /**
     * json库
     */
    implementation libs.gw.json.kit

    /**
     * json数据解析
     */
    compileOnly(libs.moshi.kotlin)

    /**
     * adapter
     */
    implementation libs.recyclerview.adapter.helper

    // 技威生命周期管理
    implementation libs.gw.base.lifecycle

    // 图片加载框架
    implementation libs.glide
}

dependencies {
    implementation project(":component_modules:component_family_api")
    implementation project(":component_modules:component_account_api")
    implementation project(":component_modules:component_mine_api")
    implementation project(":component_modules:component_device_share_api")
    implementation project(":component_modules:component_msg_api")
    implementation project(":component_modules:component_config_api")

    implementation(libs.reoqoo.component.webview.api)
    implementation(libs.reoqoo.component.plugin.service.api)
    implementation(libs.reoqoo.component.config.net.api)
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)
}