apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"
apply plugin: "androidx.navigation.safeargs.kotlin"

def isApplication = project.name == debug_module_name

android {
    namespace "com.gw_reoqoo.cp_account"

    /**
     * 资源文件前缀
     */
    resourcePrefix("account_")
}

dependencies {
    /**
     * json库
     */
    implementation libs.gw.json.kit

    /**
     * 云存相关
     */
    implementation libs.gw.iot.vas

    /**
     * 技威生命周期管理
     */
    implementation libs.gw.base.lifecycle

    /**
     * 技威数据统计
     */
    implementation libs.gw.base.statistics

    /**
     * adapter
     */
    implementation libs.recyclerview.adapter.helper

    /**
     * json工具类
     */
    implementation(libs.moshi.kotlin)
}

dependencies {
    implementation project(path: ":component_modules:component_account_api")
    implementation project(path: ":component_modules:component_config_api")
    implementation project(path: ":component_modules:component_mine_api")
    implementation project(path: ":component_modules:component_push_api")

    implementation(libs.reoqoo.component.debug.api)
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)
    implementation(libs.reoqoo.component.webview.api)
    implementation(libs.reoqoo.component.website.api)
    implementation(libs.reoqoo.component.plugin.service.api)
}

dependencies {
    implementation(libs.reoqoo.lib.utils)
    implementation(libs.reoqoo.lib.widget)
    implementation(libs.reoqoo.lib.room)
    implementation(libs.reoqoo.lib.http)
    implementation(libs.reoqoo.lib.iotvideo)
    implementation(libs.reoqoo.lib.webview)
//    if (isApplication) {
//        // 屏幕适配
//        implementation libs.auto.size
//    }
}