apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"
def isApplication = project.name == debug_module_name
android {
    namespace 'com.gw_reoqoo.component_house_watch'
    defaultConfig {
        if (isApplication) {
            applicationId "com.gw_reoqoo.component_house_watch"
        }
    }
    /**
     * 资源文件前缀
     */
    resourcePrefix("house_watch_")
}

dependencies {
    /**
     * 云存相关
     */
    implementation libs.gw.iot.vas
}

dependencies {
    implementation libs.glide
    // 下拉刷新上拉加载 核心必须依赖
    implementation libs.refresh.layout.kernel

    implementation(libs.moshi.kotlin)

    implementation(libs.lottie) {
        exclude group: 'androidx.lifecycle'
        exclude group: 'androidx.appcompat'
        exclude group: 'androidx.activity'
        exclude group: 'androidx.core'
        exclude group: 'androidx.annotation'
    }
    // RecyclerView流式布局
    implementation libs.flexbox
}

dependencies {
    implementation(project(":lib_modules:lib_resource"))

    implementation(libs.reoqoo.lib.router)
    implementation(libs.reoqoo.lib.architecture)
    compileOnly(libs.reoqoo.lib.qrcode)
    implementation(libs.reoqoo.lib.cloud.player)
}

dependencies {
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)
    implementation(libs.reoqoo.component.plugin.service.api)

    implementation project(path: ':component_modules:component_family_api')
    implementation project(path: ':component_modules:component_account_api')
    implementation project(path: ":component_modules:component_house_watch_api")
    implementation project(path: ":component_modules:component_config_api")
    implementation project(path: ":component_modules:component_push_api")
    implementation project(path: ":component_modules:component_device_share_api")
}