apply from: "${rootDir.absolutePath}/script/gradle/component_depends.gradle"
def isApplication = project.name == debug_module_name

android {
    namespace 'com.gw_reoqoo.component_family'
    defaultConfig {
        if (isApplication) {
            applicationId "com.gw_reoqoo.component_family"
        }
    }
    /**
     * 资源文件前缀
     */
    resourcePrefix("family_")
}

dependencies {
    implementation project(":lib_modules:lib_resource")

    implementation(libs.reoqoo.lib.router)
    implementation(libs.reoqoo.lib.room)
    compileOnly(libs.reoqoo.lib.qrcode)
    implementation(libs.reoqoo.lib.architecture)
    implementation(libs.reoqoo.lib.http)
    implementation(libs.reoqoo.lib.iotvideo)
    implementation(libs.reoqoo.lib.webview)
}

dependencies {
    /**
     * json库
     */
    implementation libs.gw.json.kit

    implementation libs.glide

    compileOnly(libs.moshi.kotlin)

    compileOnly libs.gw.base.lifecycle

    implementation(libs.lottie) {
        exclude group: 'androidx.lifecycle'
        exclude group: 'androidx.appcompat'
        exclude group: 'androidx.activity'
        exclude group: 'androidx.core'
        exclude group: 'androidx.annotation'
    }
}

dependencies {
    implementation project(path: ':component_modules:component_family_api')
    implementation project(path: ':component_modules:component_account_api')
    implementation project(path: ":component_modules:component_config_api")
    implementation project(path: ":component_modules:component_msg_api")
    implementation project(path: ":component_modules:component_push_api")
    implementation project(path: ":component_modules:component_mine_api")
    implementation project(path: ":component_modules:component_device_share_api")

    implementation(libs.reoqoo.component.upgrade.api)
    implementation(libs.reoqoo.component.iotapi.plugin.opt.api)

    implementation(libs.reoqoo.component.plugin.service.api)
    implementation(libs.reoqoo.component.config.net.api)
    implementation(libs.reoqoo.component.webview.api)
    implementation(libs.reoqoo.component.website.api)
    implementation(libs.reoqoo.component.debug.api)
    implementation(libs.reoqoo.component.iotapi.plugin.api)
}

dependencies {
    implementation libs.blur.view
}