apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.dagger.hilt.android'
apply plugin: 'therouter'

import com.gw.buildsrc.dependlibs.GwDependLibs
import com.gw.buildsrc.version.Versions

android {
    compileSdkVersion Versions.BuildVersions.VERSION_COMPILE_SDK
    defaultConfig {
        minSdkVersion Versions.BuildVersions.VERSION_MIN_SDK
        targetSdkVersion Versions.BuildVersions.VERSION_TARGET_SDK
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        // for view binding :
        dataBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    // Allow references to generated code
    kapt {
        correctErrorTypes true
    }

    packagingOptions {

        // xlog
        pickFirst 'lib/armeabi/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'

        pickFirst 'lib/armeabi/libgwmarsxlog.so'
        pickFirst 'lib/armeabi-v7a/libgwmarsxlog.so'
        pickFirst 'lib/arm64-v8a/libgwmarsxlog.so'

        // 自研播放器
        pickFirst 'lib/armeabi-v7a/libavcodec.so'
        pickFirst 'lib/armeabi/libavcodec.so'
        pickFirst 'lib/arm64-v8a/libavcodec.so'

        pickFirst 'lib/armeabi-v7a/libavfilter.so'
        pickFirst 'lib/armeabi/libavfilter.so'
        pickFirst 'lib/arm64-v8a/libavfilter.so'

        pickFirst 'lib/armeabi-v7a/libavformat.so'
        pickFirst 'lib/armeabi/libavformat.so'
        pickFirst 'lib/arm64-v8a/libavformat.so'

        pickFirst 'lib/armeabi-v7a/libavutil.so'
        pickFirst 'lib/armeabi/libavutil.so'
        pickFirst 'lib/arm64-v8a/libavutil.so'

        pickFirst 'lib/armeabi-v7a/libcrypto.1.1.so'
        pickFirst 'lib/armeabi/libcrypto.1.1.so'
        pickFirst 'lib/arm64-v8a/libcrypto.1.1.so'

        pickFirst 'lib/armeabi-v7a/libgwbase.so'
        pickFirst 'lib/armeabi/libgwbase.so'
        pickFirst 'lib/arm64-v8a/libgwbase.so'

        pickFirst 'lib/armeabi-v7a/libssl.1.1.so'
        pickFirst 'lib/armeabi/libssl.1.1.so'
        pickFirst 'lib/arm64-v8a/libssl.1.1.so'

        pickFirst 'lib/armeabi-v7a/libswresample.so'
        pickFirst 'lib/armeabi/libswresample.so'
        pickFirst 'lib/arm64-v8a/libswresample.so'

        pickFirst 'lib/armeabi-v7a/libswscale.so'
        pickFirst 'lib/armeabi/libswscale.so'
        pickFirst 'lib/arm64-v8a/libswscale.so'

        pickFirst 'lib/armeabi-v7a/libxml2.so'
        pickFirst 'lib/armeabi/libxml2.so'
        pickFirst 'lib/arm64-v8a/libxml2.so'

        pickFirst 'lib/armeabi-v7a/libgwplayer.so'
        pickFirst 'lib/armeabi/libgwplayer.so'
        pickFirst 'lib/arm64-v8a/libgwplayer.so'
        
        pickFirst '**/libaudiodsp_dynamic.so'
        pickFirst '**/libtxTraeVoip.so'
        pickFirst '**/libcurl.so'
        pickFirst '**/libijkffmpeg.so'
        pickFirst '**/libijkplayer.so'
        pickFirst '**/libijksdl.so'
        pickFirst '**/libbleconfig.so'
        pickFirst '**/libiotvideomulti.so'
        pickFirst '**/libmbedtls.so'

        exclude 'META-INF/DEPENDENCIES'
    }
}

/**
 * android库
 */
dependencies {

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation libs.kotlin.stdlib
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.recyclerview

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // 依赖注入框架
    implementation(libs.hilt.android, {
        exclude group: ("androidx.lifecycle")
    })
    kapt libs.hilt.compiler

}

/**
 * 第三方库
 */
dependencies {
    // 路由框架
    kapt libs.therouter.apt
    implementation libs.therouter
    // 状态栏适配器
    implementation libs.ultimate.bar.x
    // 屏幕适配
    implementation libs.auto.size
    // 内存泄露检测
    // debugImplementation libs.leakcanary
}

/**
 * 技威仓库
 */
dependencies {
    /**
     * 技威日志打印库（需要提前初始化）
     */
    implementation libs.gw.log.adapter

    /**
     * 技威工具库（不需要单独初始化）
     */
    implementation libs.gw.base.utils

    /**
     * 崩溃收集和日志上传(需要提前初始化日志路径等参数)
     */
    implementation libs.gw.crash

    /**
     * 技威数据统计
     */
    implementation libs.gw.statistics

    /**
     * 技威生命周期管理
     */
    implementation libs.gw.base.lifecycle

    /**
     * 技威网络请求
     */
    implementation libs.gw.account.mgr

    /**
     * IoTVideo库
     */
    implementation libs.gw.iot.video
}

/**
 * 模块依赖
 */
dependencies {
    implementation(project(":lib_modules:lib_api_root"))
    implementation(project(":lib_modules:lib_resource"))

    implementation("${GwDependLibs.GwLibs.DEPEND_LIB_API_COMPONENT}:lib_module_mounter:${Versions.ReoqooSdkVer.VERSION_CODE}")
    implementation("${GwDependLibs.GwLibs.DEPEND_LIB_API_COMPONENT}:lib_iotvideo:${Versions.ReoqooSdkVer.VERSION_CODE}")
}