apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'com.google.dagger.hilt.android'
apply plugin: 'therouter'

android {
    compileSdk = libs.versions.compileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildTools.get()
    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()
        targetSdk = libs.versions.targetSdk.get().toInteger()
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        // for view binding :
        dataBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    packagingOptions {

        // xlog
        pickFirst 'lib/armeabi/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'

        pickFirst 'lib/armeabi/libgwmarsxlog.so'
        pickFirst 'lib/armeabi-v7a/libgwmarsxlog.so'
        pickFirst 'lib/arm64-v8a/libgwmarsxlog.so'

        // 自研播放器
        pickFirst 'lib/armeabi-v7a/libavcodec.so'
        pickFirst 'lib/armeabi/libavcodec.so'
        pickFirst 'lib/arm64-v8a/libavcodec.so'

        pickFirst 'lib/armeabi-v7a/libavfilter.so'
        pickFirst 'lib/armeabi/libavfilter.so'
        pickFirst 'lib/arm64-v8a/libavfilter.so'

        pickFirst 'lib/armeabi-v7a/libavformat.so'
        pickFirst 'lib/armeabi/libavformat.so'
        pickFirst 'lib/arm64-v8a/libavformat.so'

        pickFirst 'lib/armeabi-v7a/libavutil.so'
        pickFirst 'lib/armeabi/libavutil.so'
        pickFirst 'lib/arm64-v8a/libavutil.so'

        pickFirst 'lib/armeabi-v7a/libcrypto.1.1.so'
        pickFirst 'lib/armeabi/libcrypto.1.1.so'
        pickFirst 'lib/arm64-v8a/libcrypto.1.1.so'

        pickFirst 'lib/armeabi-v7a/libgwbase.so'
        pickFirst 'lib/armeabi/libgwbase.so'
        pickFirst 'lib/arm64-v8a/libgwbase.so'

        pickFirst 'lib/armeabi-v7a/libssl.1.1.so'
        pickFirst 'lib/armeabi/libssl.1.1.so'
        pickFirst 'lib/arm64-v8a/libssl.1.1.so'

        pickFirst 'lib/armeabi-v7a/libswresample.so'
        pickFirst 'lib/armeabi/libswresample.so'
        pickFirst 'lib/arm64-v8a/libswresample.so'

        pickFirst 'lib/armeabi-v7a/libswscale.so'
        pickFirst 'lib/armeabi/libswscale.so'
        pickFirst 'lib/arm64-v8a/libswscale.so'

        pickFirst 'lib/armeabi-v7a/libxml2.so'
        pickFirst 'lib/armeabi/libxml2.so'
        pickFirst 'lib/arm64-v8a/libxml2.so'

        pickFirst '**/libcurl.so'
        pickFirst '**/libgwplayer.so'
        pickFirst '**/libiotvideomulti.so'
        pickFirst '**/libmbedtls.so'

        exclude 'META-INF/DEPENDENCIES'
    }
}

/**
 * android库
 */
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation libs.kotlin.stdlib
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.recyclerview

    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // 依赖注入框架
    implementation(libs.hilt.android) {
        exclude group: ("androidx.lifecycle")
    }
    ksp libs.hilt.compiler

}

/**
 * 第三方库
 */
dependencies {
    // 路由框架
    ksp libs.therouter.apt
    implementation libs.therouter
    // 状态栏适配器
    implementation libs.ultimate.bar.x
    // 屏幕适配
    implementation libs.auto.size

//    api("com.gwell:aar_plugin_service:${Versions.ThirdVersions.VERSION_PT_PLUGIN}") {
//        exclude group: 'com.tencentcs'
//        exclude group: 'org.permissionsdispatcher'
//    }
}

/**
 * 模块依赖
 */
dependencies {
    implementation(project(":lib_modules:lib_api_root"))
    implementation(project(":lib_modules:lib_resource"))

    implementation(libs.reoqoo.lib.module.mounter)
    implementation(libs.reoqoo.lib.utils)
    implementation(libs.reoqoo.lib.iotvideo)
}

dependencies {
    /**
     * IoTVideo库
     */
    implementation libs.gw.iot.video

    implementation libs.gw.account.mgr

    implementation libs.gw.log.adapter

    implementation libs.gw.base.utils

    implementation libs.gw.base.crash
    implementation libs.gw.base.lifecycle
    implementation libs.gw.base.statistics
}