apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'


import com.gw.buildsrc.dependlibs.GwDependLibs
import com.gw.buildsrc.version.Versions

android {
    compileSdkVersion Versions.BuildVersions.VERSION_COMPILE_SDK
    defaultConfig {
        minSdkVersion Versions.BuildVersions.VERSION_MIN_SDK
        targetSdkVersion Versions.BuildVersions.VERSION_TARGET_SDK
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    flavorDimensions += "version"
    productFlavors {

        create("google") {
            dimension = "version"
        }

        create("iptime") {
            dimension = "version"
        }
    }

    packagingOptions {
        // xlog
        pickFirst 'lib/armeabi/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi/libgwmarsxlog.so'
        pickFirst 'lib/armeabi-v7a/libgwmarsxlog.so'
        pickFirst 'lib/arm64-v8a/libgwmarsxlog.so'

        exclude 'META-INF/DEPENDENCIES'
    }
}

/**
 * android组件依赖
 */
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation libs.kotlin.stdlib
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.recyclerview
    implementation libs.material
    implementation libs.androidx.lifecycle.runtime.ktx
}

/**
 * 第三方库依赖
 */
dependencies {
}

/**
 * 技威仓库依赖
 */
dependencies {
    /**
     * 日志库
     */
    implementation libs.gw.log.adapter
    /**
     * 工具库
     */
    implementation libs.gw.base.utils
    /**
     * json库
     */
    implementation libs.gw.json.kit
}